// Code generated by MockGen. DO NOT EDIT.
// Source: C:/Users/thali/fiap/api-microservice-catalog/microservice/internal/shared/interfaces/file-provider.interface.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIFileProvider is a mock of IFileProvider interface.
type MockIFileProvider struct {
	ctrl     *gomock.Controller
	recorder *MockIFileProviderMockRecorder
}

// MockIFileProviderMockRecorder is the mock recorder for MockIFileProvider.
type MockIFileProviderMockRecorder struct {
	mock *MockIFileProvider
}

// NewMockIFileProvider creates a new mock instance.
func NewMockIFileProvider(ctrl *gomock.Controller) *MockIFileProvider {
	mock := &MockIFileProvider{ctrl: ctrl}
	mock.recorder = &MockIFileProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIFileProvider) EXPECT() *MockIFileProviderMockRecorder {
	return m.recorder
}

// DeleteFile mocks base method.
func (m *MockIFileProvider) DeleteFile(fileName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFile", fileName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFile indicates an expected call of DeleteFile.
func (mr *MockIFileProviderMockRecorder) DeleteFile(fileName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFile", reflect.TypeOf((*MockIFileProvider)(nil).DeleteFile), fileName)
}

// DeleteFiles mocks base method.
func (m *MockIFileProvider) DeleteFiles(filenames []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFiles", filenames)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFiles indicates an expected call of DeleteFiles.
func (mr *MockIFileProviderMockRecorder) DeleteFiles(filenames interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFiles", reflect.TypeOf((*MockIFileProvider)(nil).DeleteFiles), filenames)
}

// GetPresignedURL mocks base method.
func (m *MockIFileProvider) GetPresignedURL(fileName string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPresignedURL", fileName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPresignedURL indicates an expected call of GetPresignedURL.
func (mr *MockIFileProviderMockRecorder) GetPresignedURL(fileName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPresignedURL", reflect.TypeOf((*MockIFileProvider)(nil).GetPresignedURL), fileName)
}

// UploadFile mocks base method.
func (m *MockIFileProvider) UploadFile(fileName string, fileContent []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadFile", fileName, fileContent)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadFile indicates an expected call of UploadFile.
func (mr *MockIFileProviderMockRecorder) UploadFile(fileName, fileContent interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadFile", reflect.TypeOf((*MockIFileProvider)(nil).UploadFile), fileName, fileContent)
}
