// Code generated by MockGen. DO NOT EDIT.
// Source: C:/Users/thali/fiap/api-microservice-catalog/microservice/internal/product/interfaces/product-data-source.interface.go

// Package mocks_interfaces is a generated GoMock package.
package mock_interfaces

import (
	reflect "reflect"
	daos "tech_challenge/internal/product/daos"

	gomock "github.com/golang/mock/gomock"
)

// MockIProductDataSource is a mock of IProductDataSource interface.
type MockIProductDataSource struct {
	ctrl     *gomock.Controller
	recorder *MockIProductDataSourceMockRecorder
}

// MockIProductDataSourceMockRecorder is the mock recorder for MockIProductDataSource.
type MockIProductDataSourceMockRecorder struct {
	mock *MockIProductDataSource
}

// NewMockIProductDataSource creates a new mock instance.
func NewMockIProductDataSource(ctrl *gomock.Controller) *MockIProductDataSource {
	mock := &MockIProductDataSource{ctrl: ctrl}
	mock.recorder = &MockIProductDataSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIProductDataSource) EXPECT() *MockIProductDataSourceMockRecorder {
	return m.recorder
}

// AddProductImage mocks base method.
func (m *MockIProductDataSource) AddProductImage(productImage daos.ProductImageDAO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddProductImage", productImage)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddProductImage indicates an expected call of AddProductImage.
func (mr *MockIProductDataSourceMockRecorder) AddProductImage(productImage interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddProductImage", reflect.TypeOf((*MockIProductDataSource)(nil).AddProductImage), productImage)
}

// Delete mocks base method.
func (m *MockIProductDataSource) Delete(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIProductDataSourceMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIProductDataSource)(nil).Delete), id)
}

// DeleteImage mocks base method.
func (m *MockIProductDataSource) DeleteImage(imageFileName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteImage", imageFileName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteImage indicates an expected call of DeleteImage.
func (mr *MockIProductDataSourceMockRecorder) DeleteImage(imageFileName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteImage", reflect.TypeOf((*MockIProductDataSource)(nil).DeleteImage), imageFileName)
}

// FindAll mocks base method.
func (m *MockIProductDataSource) FindAll() ([]daos.ProductDAO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll")
	ret0, _ := ret[0].([]daos.ProductDAO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockIProductDataSourceMockRecorder) FindAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockIProductDataSource)(nil).FindAll))
}

// FindAllByCategoryID mocks base method.
func (m *MockIProductDataSource) FindAllByCategoryID(categoryID string) ([]daos.ProductDAO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllByCategoryID", categoryID)
	ret0, _ := ret[0].([]daos.ProductDAO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllByCategoryID indicates an expected call of FindAllByCategoryID.
func (mr *MockIProductDataSourceMockRecorder) FindAllByCategoryID(categoryID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllByCategoryID", reflect.TypeOf((*MockIProductDataSource)(nil).FindAllByCategoryID), categoryID)
}

// FindAllImagesProductById mocks base method.
func (m *MockIProductDataSource) FindAllImagesProductById(productID string) ([]daos.ProductImageDAO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllImagesProductById", productID)
	ret0, _ := ret[0].([]daos.ProductImageDAO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllImagesProductById indicates an expected call of FindAllImagesProductById.
func (mr *MockIProductDataSourceMockRecorder) FindAllImagesProductById(productID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllImagesProductById", reflect.TypeOf((*MockIProductDataSource)(nil).FindAllImagesProductById), productID)
}

// FindByID mocks base method.
func (m *MockIProductDataSource) FindByID(id string) (daos.ProductDAO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(daos.ProductDAO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockIProductDataSourceMockRecorder) FindByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockIProductDataSource)(nil).FindByID), id)
}

// Insert mocks base method.
func (m *MockIProductDataSource) Insert(product daos.ProductDAO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", product)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockIProductDataSourceMockRecorder) Insert(product interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockIProductDataSource)(nil).Insert), product)
}

// SetAllPreviousImagesAsNotDefault mocks base method.
func (m *MockIProductDataSource) SetAllPreviousImagesAsNotDefault(productID, exceptImageID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetAllPreviousImagesAsNotDefault", productID, exceptImageID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetAllPreviousImagesAsNotDefault indicates an expected call of SetAllPreviousImagesAsNotDefault.
func (mr *MockIProductDataSourceMockRecorder) SetAllPreviousImagesAsNotDefault(productID, exceptImageID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAllPreviousImagesAsNotDefault", reflect.TypeOf((*MockIProductDataSource)(nil).SetAllPreviousImagesAsNotDefault), productID, exceptImageID)
}

// SetImageAsDefault mocks base method.
func (m *MockIProductDataSource) SetImageAsDefault(productID, imageID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetImageAsDefault", productID, imageID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetImageAsDefault indicates an expected call of SetImageAsDefault.
func (mr *MockIProductDataSourceMockRecorder) SetImageAsDefault(productID, imageID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetImageAsDefault", reflect.TypeOf((*MockIProductDataSource)(nil).SetImageAsDefault), productID, imageID)
}

// Update mocks base method.
func (m *MockIProductDataSource) Update(product daos.ProductDAO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", product)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIProductDataSourceMockRecorder) Update(product interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIProductDataSource)(nil).Update), product)
}

// ImageIsDefault mocks base method.
func (m *MockIProductDataSource) ImageIsDefault(imageFileName string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImageIsDefault", imageFileName)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ImageIsDefault indicates an expected call of ImageIsDefault.
func (mr *MockIProductDataSourceMockRecorder) ImageIsDefault(imageFileName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImageIsDefault", reflect.TypeOf((*MockIProductDataSource)(nil).ImageIsDefault), imageFileName)
}

// DeleteProductImage mocks base method.
func (m *MockIProductDataSource) DeleteProductImage(imageFileName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProductImage", imageFileName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProductImage indicates an expected call of DeleteProductImage.
func (mr *MockIProductDataSourceMockRecorder) DeleteProductImage(imageFileName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProductImage", reflect.TypeOf((*MockIProductDataSource)(nil).DeleteProductImage), imageFileName)
}
