// Code generated by MockGen. DO NOT EDIT.
// Adaptado para produtos
// Source: internal/interfaces/data-source.interface.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	reflect "reflect"
	daos "tech_challenge/internal/product/daos"

	gomock "github.com/golang/mock/gomock"
)

// MockIProductDataSource is a mock of IProductDataSource interface.
type MockIProductDataSource struct {
	ctrl     *gomock.Controller
	recorder *MockIProductDataSourceMockRecorder
}

// MockIProductDataSourceMockRecorder is the mock recorder for MockIProductDataSource.
type MockIProductDataSourceMockRecorder struct {
	mock *MockIProductDataSource
}

// NewMockIProductDataSource creates a new mock instance.
func NewMockIProductDataSource(ctrl *gomock.Controller) *MockIProductDataSource {
	mock := &MockIProductDataSource{ctrl: ctrl}
	mock.recorder = &MockIProductDataSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIProductDataSource) EXPECT() *MockIProductDataSourceMockRecorder {
	return m.recorder
}

// Insert mocks base method.
func (m *MockIProductDataSource) Insert(product daos.ProductDAO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", product)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockIProductDataSourceMockRecorder) Insert(product interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockIProductDataSource)(nil).Insert), product)
}

// Delete mocks base method.
func (m *MockIProductDataSource) Delete(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIProductDataSourceMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIProductDataSource)(nil).Delete), id)
}

// FindAll mocks base method.
func (m *MockIProductDataSource) FindAll() ([]daos.ProductDAO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll")
	ret0, _ := ret[0].([]daos.ProductDAO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockIProductDataSourceMockRecorder) FindAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockIProductDataSource)(nil).FindAll))
}

// FindByID mocks base method.
func (m *MockIProductDataSource) FindByID(id string) (daos.ProductDAO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(daos.ProductDAO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockIProductDataSourceMockRecorder) FindByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockIProductDataSource)(nil).FindByID), id)
}

// Update mocks base method.
func (m *MockIProductDataSource) Update(product daos.ProductDAO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", product)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIProductDataSourceMockRecorder) Update(product interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIProductDataSource)(nil).Update), product)
}
