// Code generated by MockGen. DO NOT EDIT.
// Adaptado para categorias
// Source: internal/interfaces/data-source.interface.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	reflect "reflect"
	daos "tech_challenge/internal/product/daos"

	gomock "github.com/golang/mock/gomock"
)

// MockICategoryDataSource is a mock of ICategoryDataSource interface.
type MockICategoryDataSource struct {
	ctrl     *gomock.Controller
	recorder *MockICategoryDataSourceMockRecorder
}

// MockICategoryDataSourceMockRecorder is the mock recorder for MockICategoryDataSource.
type MockICategoryDataSourceMockRecorder struct {
	mock *MockICategoryDataSource
}

// NewMockICategoryDataSource creates a new mock instance.
func NewMockICategoryDataSource(ctrl *gomock.Controller) *MockICategoryDataSource {
	mock := &MockICategoryDataSource{ctrl: ctrl}
	mock.recorder = &MockICategoryDataSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICategoryDataSource) EXPECT() *MockICategoryDataSourceMockRecorder {
	return m.recorder
}

// Insert mocks base method.
func (m *MockICategoryDataSource) Insert(category daos.CategoryDAO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", category)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockICategoryDataSourceMockRecorder) Insert(category interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockICategoryDataSource)(nil).Insert), category)
}

// Delete mocks base method.
func (m *MockICategoryDataSource) Delete(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockICategoryDataSourceMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockICategoryDataSource)(nil).Delete), id)
}

// FindAll mocks base method.
func (m *MockICategoryDataSource) FindAll() ([]daos.CategoryDAO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll")
	ret0, _ := ret[0].([]daos.CategoryDAO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockICategoryDataSourceMockRecorder) FindAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockICategoryDataSource)(nil).FindAll))
}

// FindByID mocks base method.
func (m *MockICategoryDataSource) FindByID(id string) (daos.CategoryDAO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(daos.CategoryDAO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockICategoryDataSourceMockRecorder) FindByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockICategoryDataSource)(nil).FindByID), id)
}

// Update mocks base method.
func (m *MockICategoryDataSource) Update(category daos.CategoryDAO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", category)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockICategoryDataSourceMockRecorder) Update(category interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockICategoryDataSource)(nil).Update), category)
}
